#! bin/bash/python

import chess
import chess.engine

engine = chess.engine.SimpleEngine.popen_uci("./stockfish/stockfish-ubuntu-x86-64-sse41-popcnt")
limit = chess.engine.Limit(time=2.0)
#engine.play(board, limit)
board = chess.Board()

print(board)

board.push(e4)

print(board)

